export const posts = [
    {
      title: "Benefits of Virtual CFO Services For Startups, SMEs & Businesses",
      slug: "benefits-of-virtual-cfo-services",
      link: "https://inspirigence.in/benefits-of-virtual-cfo-services/",
      created_at: "2022-04-08 09:00:41",
      author: "MIsORENt",
      content: "Digital technologies are causing new SME demands...",
      categories: ["Blogs", "Virtual CFO services"],
      meta_description: "Before we get into Benefits of Virtual CFO Services...",
      featured_image: "https://inspirigence.in/wp-content/uploads/2022/04/virtual-cfo-services-in-india.jpg",
    },
    {
      title: "How To Launch IPO? - Complete Process, Eligibility 2025",
      slug: "how-to-launch-ipo-in-india",
      link: "https://inspirigence.in/how-to-launch-ipo-in-india/",
      created_at: "2022-06-16 09:51:01",
      author: "MIsORENt",
      content: "The company will become a publicly traded corporation...",
      categories: ["Blogs", "IPO in India"],
      meta_description: "Unlock the secrets of IPO with our step-by-step guide!",
      featured_image: "https://inspirigence.in/wp-content/uploads/2022/06/INSPIRIGENCE.jpg.webp",
    },
    {
      title: "10 Factors to Consider When Choosing A Financial Advisor in India",
      slug: "factors-to-consider-when-choosing-a-financial-advisor",
      link: "https://inspirigence.in/factors-to-consider-when-choosing-a-financial-advisor/",
      created_at: "2024-02-02 11:48:47",
      author: "MIsORENt",
      content: "Choosing the right economic guide will have an impact...",
      categories: ["Blogs"],
      meta_description: "Looking For Financial Advisor In India? Here Are 10 Factors...",
      featured_image: "https://inspirigence.in/wp-content/uploads/2024/02/financial-advisor-knowledge-and-qualification.webp",
    },
    {
      title: "Why AIFs Have Become Popular Among HNIs?",
      slug: "why-aifs-have-become-popular-among-hnis",
      link: "https://inspirigence.in/why-aifs-have-become-popular-among-hnis/",
      created_at: "2024-03-21 11:50:27",
      author: "MIsORENt",
      content: "Over the past few years, Alternative Investment Funds...",
      categories: ["Blogs"],
      meta_description: "Wondering why AIFs have become popular among HNIs?",
      featured_image: "https://inspirigence.in/wp-content/uploads/2024/03/HNIsHigh-Net-Worth-Individuals.webp",
    },
    {
      title: "Difference Between Mergers & Acquisitions",
      slug: "difference-between-mergers-and-acquisitions",
      link: "https://inspirigence.in/difference-between-mergers-and-acquisitions/",
      created_at: "2024-04-10 10:24:05",
      author: "MIsORENt",
      content: "In the dynamic world of business, organisations are always looking for ways to grow...",
      categories: ["Blogs"],
      meta_description: "Discover the Difference between mergers and acquisitions...",
      featured_image: "https://inspirigence.in/wp-content/uploads/2024/04/Mergers-and-Acquisitions.jpg",
    },
    {
      title: "Understanding Private Equity & How To Invest In It?",
      slug: "understanding-private-equity",
      link: "https://inspirigence.in/understanding-private-equity/",
      created_at: "2024-05-08 11:18:36",
      author: "MIsORENt",
      content: "Private equity (PE) represents a financing approach...",
      categories: ["Blogs"],
      meta_description: "In this blog 'Understanding Private Equity & How to Invest in it?'...",
      featured_image: "https://inspirigence.in/wp-content/uploads/2024/05/what-is-private-equity-and-its-risks.jpg",
    },
    {
      title: "SME IPO Process: A Step-by-Step Guide!",
      slug: "sme-ipo-process",
      link: "https://inspirigence.in/sme-ipo-process/",
      created_at: "2024-06-19 12:13:06",
      author: "MIsORENt",
      content: "Small and Medium Enterprises (SMEs) are essential contributors...",
      categories: ["Blogs"],
      meta_description: "Launch Your SME IPO With Expertise! Learn SME IPO Process...",
      featured_image: "https://inspirigence.in/wp-content/uploads/2024/06/SME-IPO-Process-2.jpg",
    },
    {
      title: "Experience Explosive Business Growth With Optimized Corporate Finance",
      slug: "explosive-business-growth-with-optimized-corporate-finance",
      link: "https://inspirigence.in/explosive-business-growth-with-optimized-corporate-finance/",
      created_at: "2024-08-05 12:33:15",
      author: "MIsORENt",
      content: "In the ever-evolving landscape of business, optimized corporate finances...",
      categories: ["Blogs"],
      meta_description: "Unlock your business's full potential with optimized corporate finance...",
      featured_image: "https://inspirigence.in/wp-content/uploads/2024/07/Optimized-Corporate-Finance.jpg",
    },
    {
      title: "Merger and Acquisition Valuation Methods: Choosing the Right Approach",
      slug: "merger-and-acquisition-valuation-methods",
      link: "https://inspirigence.in/merger-and-acquisition-valuation-methods/",
      created_at: "2024-08-05 12:32:46",
      author: "MIsORENt",
      content: "Achieving a successful merger or acquisition (M&A) hinges on one crucial factor...",
      categories: ["Blogs"],
      meta_description: "Master the art of Merger and Acquisition valuation with our expert guide...",
      featured_image: "https://inspirigence.in/wp-content/uploads/2024/07/mergers-and-acquisition-valuation.jpg",
    },
    {
      title: "The Role of Fund Accounting Services in Financial Transparency",
      slug: "role-of-fund-accounting-services-in-financial-transparency",
      link: "https://inspirigence.in/role-of-fund-accounting-services-in-financial-transparency/",
      created_at: "2024-08-22 13:01:30",
      author: "MIsORENt",
      content: "In today's fast-paced financial landscape, transparency and accuracy...",
      categories: ["Blogs"],
      meta_description: "How fund accounting ensures financial transparency? Here is everything...",
      featured_image: "https://inspirigence.in/wp-content/uploads/2024/08/The-Role-of-Fund-Accounting-Services-in-Financial-Transparency.jpg.webp",
    },
    {
      title: "What is an IPO (Initial Public Offering) & How it Works?",
      slug: "what-is-an-ipo-initial-public-offering",
      link: "https://inspirigence.in/what-is-an-ipo-initial-public-offering/",
      created_at: "2024-11-13 05:35:20",
      author: "iCHOuSPh",
      content: "An Initial Public Offering (IPO) is a significant milestone in a private company's life...",
      categories: ["Blogs"],
      meta_description: "Discover what is an IPO (Initial Public Offering), key benefits, risks...",
      featured_image: "https://inspirigence.in/wp-content/uploads/2024/11/ipo-process-and-types.jpg",
    },
    {
      title: "How to Determine If Your Business Is Ready To Launch An IPO?",
      slug: "how-to-determine-if-your-business-is-ready-to-launch-an-ipo",
      link: "https://inspirigence.in/how-to-determine-if-your-business-is-ready-to-launch-an-ipo/",
      created_at: "2024-11-13 06:17:31",
      author: "iCHOuSPh",
      content: "Making a company public is a significant milestone for any business...",
      categories: ["Blogs"],
      meta_description: "Discover how to determine if your business is ready to launch an IPO...",
      featured_image: "https://inspirigence.in/wp-content/uploads/2024/11/launch-an-IPO.jpg",
    },
    {
      title: "Factors You Must Consider Before Hiring an IPO Advisor",
      slug: "factors-you-must-consider-before-hiring-ipo-advisor",
      link: "https://inspirigence.in/factors-you-must-consider-before-hiring-ipo-advisor/",
      created_at: "2025-01-08 11:56:48",
      author: "iCHOuSPh",
      content: "Launching an Initial Public Offering (IPO) is a significant milestone...",
      categories: ["Blogs"],
      meta_description: "Discover key factors to consider before hiring an IPO advisor.",
      featured_image: "https://inspirigence.in/wp-content/uploads/2025/01/Factors-You-Must-Consider-Before-Hiring-an-IPO-Advisor.jpg.webp",
    },
    {
      title: "The Importance of Due Diligence in Mergers and Acquisitions",
      slug: "importance-of-due-diligence-in-mergers-and-acquisitions",
      link: "https://inspirigence.in/importance-of-due-diligence-in-mergers-and-acquisitions/",
      created_at: "2025-02-15 10:45:12",
      author: "iCHOuSPh",
      content: "Due diligence is a critical step in the mergers and acquisitions (M&A) process...",
      categories: ["Blogs"],
      meta_description: "Learn why due diligence is crucial in mergers and acquisitions...",
      featured_image: "https://inspirigence.in/wp-content/uploads/2025/02/due-diligence.jpg",
    },
    {
      title: "The Role of Corporate Finance in Business Growth",
      slug: "role-of-corporate-finance-in-business-growth",
      link: "https://inspirigence.in/role-of-corporate-finance-in-business-growth/",
      created_at: "2025-03-10 09:46:43",
      author: "MIsORENt",
      content: "Corporate finance plays a pivotal role in the growth and sustainability of a business...",
      categories: ["Blogs"],
      meta_description: "Understand the role of corporate finance in driving business growth...",
      featured_image: "https://inspirigence.in/wp-content/uploads/2025/03/corporate-finance.jpg",
    },
    {
      title: "The Benefits of Outsourcing CFO Services for SMEs",
      slug: "benefits-of-outsourcing-cfo-services-for-smes",
      link: "https://inspirigence.in/benefits-of-outsourcing-cfo-services-for-smes/",
      created_at: "2025-04-05 12:30:15",
      author: "MIsORENt",
      content: "Outsourcing CFO services has become a popular strategy for SMEs...",
      categories: ["Blogs"],
      meta_description: "Discover the benefits of outsourcing CFO services for SMEs...",
      featured_image: "https://inspirigence.in/wp-content/uploads/2025/04/outsourcing-cfo.jpg",
    },
    {
      title: "The Future of Private Equity in India",
      slug: "future-of-private-equity-in-india",
      link: "https://inspirigence.in/future-of-private-equity-in-india/",
      created_at: "2025-05-20 11:22:33",
      author: "iCHOuSPh",
      content: "Private equity (PE) has been a driving force in India's economic growth...",
      categories: ["Blogs"],
      meta_description: "Explore the future of private equity in India...",
      featured_image: "https://inspirigence.in/wp-content/uploads/2025/05/private-equity.jpg",
    },
    {
      title: "The Impact of AI on Financial Advisory Services",
      slug: "impact-of-ai-on-financial-advisory-services",
      link: "https://inspirigence.in/impact-of-ai-on-financial-advisory-services/",
      created_at: "2025-06-18 10:15:45",
      author: "iCHOuSPh",
      content: "Artificial Intelligence (AI) is revolutionizing the financial advisory industry...",
      categories: ["Blogs"],
      meta_description: "Learn how AI is transforming financial advisory services...",
      featured_image: "https://inspirigence.in/wp-content/uploads/2025/06/ai-financial-advisory.jpg",
    },
    {
      title: "The Role of Technology in Modern Fund Accounting",
      slug: "role-of-technology-in-modern-fund-accounting",
      link: "https://inspirigence.in/role-of-technology-in-modern-fund-accounting/",
      created_at: "2025-07-25 14:20:10",
      author: "MIsORENt",
      content: "Technology has become an integral part of modern fund accounting...",
      categories: ["Blogs"],
      meta_description: "Discover how technology is shaping modern fund accounting...",
      featured_image: "https://inspirigence.in/wp-content/uploads/2025/07/technology-fund-accounting.jpg",
    },
  ];